resolver: lts-17.8

packages:
- '.'
flags:
  Frames:
    demos: false
extra-package-dbs: []
extra-deps:
  - discrimination-0.4.1
  - vinyl-0.13.0
  - contravariant-1.5.3
  - primitive-0.7.1.0
  - StateVar-1.2.1
