name:                framestack
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- Frames >= 0.4.0
- pipes
- microlens

executables:
  framestack-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

